### ISSUE TITLE
additional warnings showing with `GRAPHILE_ENV` unset or set to production

### ISSUE THREAD

**Issue by purge** [graphile/crystal#1966] opened 2024-02-15 09:53 UTC
```
info:  
info:   GraphiQL: http://localhost:3000/graphiql {"GRAPHILE_ENV":"production"}
info:  
Load[20] uses a regular (non-async) function for 'execute'; if it never returns a promise and the list it returns never includes a promise then setting `Load[20].isSyncAndSafe = true` will improve performance. If this is not true, set `Load[20].isSyncAndSafe = false` to dismiss this message.
```

**Comment by benjie** [comment] 2024-02-19 09:28
Duplicate of https://github.com/graphile/crystal/issues/1963 ?

**Closed** 2024-02-19 11:15 UTC
Labels: 🐛 bug
