### ISSUE TITLE
Mixed use of caret symbol in versioning for `graphql` package

### ISSUE THREAD

**Issue by jsaunders92** [graphile/crystal#1748] opened 2023-09-17 15:28 UTC
It appears that there's a mix of version specifiers for the graphql package, with both `^16.1.0-experimental-stream-defer.6` and `16.1.0-experimental-stream-defer.6` being used. This inconsistency might be causing issues with the version of the package that gets installed.

Here's the output from yarn why that shows the discrepancy:

```├─ @dataplan/pg@workspace:grafast/dataplan-pg [c68fd]
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ @dataplan/pg@workspace:grafast/dataplan-pg [e4057]
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ @dataplan/pg@workspace:grafast/dataplan-pg
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ @localrepo/grafast-bench@workspace:grafast/bench
│  └─ graphql@npm:16.8.0 (via npm:^16.1.0-experimental-stream-defer.6)
│
├─ graphile-build-pg@workspace:graphile-build/graphile-build-pg [ddf1f]
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ graphile-build@workspace:graphile-build/graphile-build [ddf1f]
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ pgl@workspace:postgraphile/pgl
│  └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6)
│
├─ postgraphile@workspace:postgraphile/postgraphile [dc3d9]
│  └─ graphql@npm:16.8.0 (via npm:^16.1.0-experimental-stream-defer.6)
│
├─ postgraphile@workspace:postgraphile/postgraphile [ddf1f]
│  └─ graphql@npm:16.8.0 (via npm:^16.1.0-experimental-stream-defer.6)
│
└─ root-workspace-0b6124@workspace:.
   └─ graphql@npm:16.1.0-experimental-stream-defer.6 (via npm:16.1.0-experimental-stream-defer.6) 
  ```
   
It seems that at some point, the caret (^) symbol was omitted (or added) in the version specifier, leading to potential version mismatches.

**Comment by benjie** [comment] 2023-09-18 17:53
_Is_ this causing issues for you? It _shouldn't_ because each of the packages should import graphql from a higher package (e.g. `postgraphile` gets it from `grafast/graphql`) so in the end it should all work out.

The plan is to fix this once the new stream/defer has been implemented (which hasn't even been started yet), at which point we'll probably require GraphQL v17 as base.

**Comment by benjie** [comment] 2023-09-29 17:57
> This inconsistency might be causing issues with the version of the package that gets installed

Since it's not clear that it _is_ causing issues, I'm going to go ahead and close this as intended (since they are what I intend). If, however, it is causing issues then please reopen and explain in detail how to reproduce the issue :+1:

**Closed by benjie** 2023-09-29 17:57 UTC
Labels: ❔ question

**Comment by jsaunders92** [comment] 2023-09-29 18:10
Hi Benjie. Yes, sorry I've not got back to this yet. Life kinda got in the way in between me writing it and now. When my head is back in the game, I'll have a look and re-open if necessary. Thanks
