### ISSUE TITLE
why Postraphile isn't exposing the parent table instead of the partition tables.

### ISSUE THREAD

**Issue by divya-sk** [graphile/crystal#1996] opened 2024-03-15 06:22 UTC
we are using "postgraphile": "4.13.0", still facing the same issues

graphqlRoute: "/shield/graphql",
graphiqlRoute: "/shield/graphiql",
eventStreamRoute: "/shield/graphql/stream",
ownerConnectionString: process.env.OWNER_CONNECTION_STRING,
watchPg: true,
graphiql: true,
enhanceGraphiql: true,
pgUsePartitionParents: true,
enableCors: false,
disableWarning: true,
statement_timeout: "3600000",
appendPlugins: [
require("@graphile-contrib/pg-simplify-inflector"),
require("postgraphile-plugin-connection-filter"),
],
}
),
this is the piece of code we using.tail the issue you'd like to discuss. -->

**Comment by benjie** [comment] 2024-03-15 09:49
Duplicate of https://github.com/graphile/crystal/issues/1991; please stop double filing issues.

**Closed by benjie** 2024-03-15 09:49 UTC
Labels: 👥 duplicate
