### ISSUE TITLE
Koa middleware does not call next() for all scenarios

### ISSUE THREAD

**Issue by aryascripts** [graphile/crystal#2075] opened 2024-05-29 16:21 UTC
### Summary

Koa middlewares run sequentially, and each middleware calls next() function after using or updating the ctx (KoaContext). The issue with the grafast middleware that is added here ([koa/v2/index.ts](https://github.com/graphile/crystal/blob/91e87ab6516490a4cc7b7fc6400efb7623fbd331/grafast/grafserv/src/servers/koa/v2/index.ts#L70)) is that it only calls next() in some scenarios, and not all. In theory, all scenarios of a middleware should call next, unless it's a catastrophic error.

Once this is enabled, it allows the overall koa app to process something after grafast. This could be things like collecting metrics or logging.

### Steps to reproduce
Sample code
```typescript
  const app = new Koa();
  const pgl = postgraphile(configuration, pool);
  const serv = pgl.createServ(grafserv);
  
  const server = app.listen(port);
  await serv.addTo(app, server);

  app.use(async (ctx, next) => {
    // this will never be called for most requests
    console.log("running middleware after grafast");
  })

```

### Expected results

We should always call the next() middleware in the chain of Koa middlewares.

### Actual results

Currently, we only call next middleware if result from graphile is `null`
https://github.com/graphile/crystal/blob/91e87ab6516490a4cc7b7fc6400efb7623fbd331/grafast/grafserv/src/servers/koa/v2/index.ts#L79-L81

### Solution

PR here for the fix: https://github.com/graphile/crystal/pull/2073

Call next no matter what, from the grafast/graphile middleware (see PR above)

**Comment by benjie** [comment] 2024-06-04 14:16
Closing for the reasons outlined in https://github.com/graphile/crystal/pull/2073#issuecomment-2147648116

The code can be fixed by moving the middleware before PostGraphile:

```ts
  const app = new Koa();

  // 👇👇👇
  app.use(async (ctx, next) => {
    console.log("running middleware BEFORE grafast");
    await next(); // 👈👈 this is where PostGraphile/Grafast would run
    console.log("running middleware AFTER grafast");
  })
  // 👆👆👆

  const pgl = postgraphile(configuration, pool);
  const serv = pgl.createServ(grafserv);
  
  const server = app.listen(port);
  await serv.addTo(app, server);
```

**Closed by benjie** 2024-06-04 14:16 UTC
Labels: ✖️ invalid

**Comment by aryascripts** [comment] 2024-06-04 17:46
@benjie Just to clarify, today postgraphile's middleware does not follow Koa guidelines, which my PR was trying to fix. This will be unexpected to anyone trying to use Koa + Postgraphile in the future.

I request to reconsider my changes.

From Koa's docs:
https://github.com/koajs/koa/blob/master/docs/guide.md#writing-middleware
> When the middleware is run, **it must manually invoke next()** to run the "downstream" middleware.

The middleware in this repo today, does not invoke `next()` which is not what most developers using middlewares expect.

**Comment by cassidycodes** [comment] 2024-06-04 18:21
@benjie I'm chiming in here because I work with @aryascripts. While your example in #2073 and your suggestion here is helpful and gives us something to work with, it was unexpected that PostGraphile would have a terminal middleware. I'd usually expect a terminal middleware to be written by application owners, rather than a library we use.

However, if you are set on keeping PostGraphile this way, perhaps we can contribute to documentation so that others don't run into the same problem.

**Comment by cassidycodes** [comment] 2024-06-05 14:39
@benjie Thanks for the thorough and thoughtful response. Treating postgraphile as a terminal middleware makes sense to me. The node/koa ecosystem is new to me, so thank you for linking to example projects that do the same. I started looking through them myself. The way you have suggested handling telemetry, compression, etc, aligns with my model of middleware in Rails, as well. Thanks again.

**Comment by benjie** [comment] 2024-09-17 11:42
Just to round this out; a maintainer of Koa has confirmed that PostGraphile operates in the correct way: https://github.com/koajs/koa/discussions/1819#discussioncomment-10481177
